### ISSUE TITLE
Missing copyright for Puree-Swift

### ISSUE THREAD

**Issue by giginet** [yoheimuta/BufferedLogger#8]
Hi ✋ 

This library seems to be inspired by [Puree-Swift](https://github.com/cookpad/Puree-Swift).
Some implementations are similar to that.(e.g. variable names, structures and so on.)

https://github.com/cookpad/Puree-Swift/blob/master/Sources/Puree/Output/BufferedOutput.swift
https://github.com/yoheimuta/BufferedLogger/blob/master/BufferedLogger/BufferedOutput.swift

Puree-Swift is distributed under [MIT License](https://github.com/cookpad/Puree-Swift/blob/master/LICENSE#L12-L13).
If you inspired by original Puree-Swift implementation, Please refer copyrights on README.

Thanks.

**Comment by yoheimuta** [comment]
@giginet Thank you for your kind advice.
You're right. I should have clearly mentioned my respect.

Please let me know if https://github.com/yoheimuta/BufferedLogger/compare/respect-Puree is enough whenever you have time.

**Comment by giginet** [comment]
Looks great! Thanks.

**Comment by yoheimuta** [comment]
@giginet Thank you! 🙇
